# Generated by Django 5.2.3 on 2025-07-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmovement',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
