# Generated by Django 4.2.23 on 2025-07-22 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmovement',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='banco.debtoraccount'),
        ),
        migrations.AlterField(
            model_name='accountmovement',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='accountmovement',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
