# Generated by Django 5.2 on 2025-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='transfer_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
