# Generated by Django 4.2.23 on 2025-07-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmovement',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='accountmovement',
            name='object_id',
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='account',
            field=models.ForeignKey(default=20250722, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='banco.debtoraccount'),
            preserve_default=False,
        ),
    ]
