# Generated by Django 5.2 on 2025-06-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtoraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
