# Generated by Django 5.2.3 on 2025-07-19 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoraccount',
            name='iban',
            field=models.CharField(help_text='IBAN de la cuenta', max_length=34, unique=True, validators=[django.core.validators.RegexValidator(message='IBAN inválido', regex='^[A-Z]{2}[0-9A-Z]{13,32}$')]),
        ),
        migrations.AlterField(
            model_name='debtoraccount',
            name='iban',
            field=models.CharField(help_text='IBAN de la cuenta', max_length=34, unique=True, validators=[django.core.validators.RegexValidator(message='IBAN inválido', regex='^[A-Z]{2}[0-9A-Z]{13,32}$')]),
        ),
    ]
