# Generated by Django 5.2.3 on 2025-06-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_debtoraccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='kid',
        ),
    ]
