# Generated by Django 5.2.3 on 2025-07-19 06:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_remove_transfer_internal_creditor_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmovement',
            name='account',
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='content_type',
            field=models.ForeignKey(default=20250719, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='object_id',
            field=models.PositiveIntegerField(default=20250719),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditoraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
