# Generated by Django 5.2.3 on 2025-06-19 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_remove_transfer_client_remove_transfer_kid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciasimulada',
            name='creditor',
        ),
        migrations.RemoveField(
            model_name='transferenciasimulada',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='transferenciasimulada',
            name='oficial',
        ),
        migrations.AddField(
            model_name='transfer',
            name='oficial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.oficialbancario'),
        ),
        migrations.DeleteModel(
            name='CreditorSimulado',
        ),
        migrations.DeleteModel(
            name='DebtorSimulado',
        ),
        migrations.DeleteModel(
            name='TransferenciaSimulada',
        ),
    ]
