# Generated by Django 5.2.3 on 2025-07-19 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_transfer_internal_creditor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='internal_creditor',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='internal_creditor_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='creditor',
            field=models.ForeignKey(default=20250720, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='banco.creditor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='creditor_account',
            field=models.ForeignKey(default=20250720, on_delete=django.db.models.deletion.PROTECT, to='banco.creditoraccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='creditor_agent',
            field=models.ForeignKey(default=20250720, on_delete=django.db.models.deletion.PROTECT, to='banco.creditoragent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='debtor_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.debtoraccount'),
        ),
    ]
