# Generated by Django 5.2.3 on 2025-07-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_otpchallenge_auth_id_alter_transfer_status'),
        ('banco', '0003_clientid_debtor_debtor_user'),
    ]

    operations = [
    ]
