# Generated by Django 4.2.23 on 2025-07-20 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_remove_transfer_internal_creditor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='internal_creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='banco.debtor'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='internal_creditor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='banco.debtoraccount'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transaction_type',
            field=models.CharField(choices=[('INTERNAL', 'Transferencia Interna'), ('EXTERNAL', 'Transferencia Externa')], default='EXTERNAL', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='banco.creditor'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='creditor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banco.creditoraccount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='creditor_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banco.creditoragent'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='debtor_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='banco.debtoraccount'),
        ),
    ]
