# Generated by Django 5.2.3 on 2025-06-20 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_remove_transferenciasimulada_creditor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DebtorSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='oficial',
        ),
        migrations.CreateModel(
            name='TransferenciaSimulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.CharField(blank=True, max_length=200)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.creditorsimulado')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.debtorsimulado')),
                ('oficial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.oficialbancario')),
            ],
        ),
    ]
