# Generated by Django 5.2.3 on 2025-06-21 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco", "0005_creditorsimulado_debtorsimulado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtorsimulado",
            name="saldo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="MovimientoDeudor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("DEPOSITO", "Depósito"), ("PAGO", "Pago")],
                        max_length=10,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "debtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="banco.debtorsimulado",
                    ),
                ),
            ],
        ),
    ]