"""
Django settings for simulador_banco project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


# Carga variables de entorno desde .env en el directorio raíz de proyecto
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

def get_env(var_name, default=None, required=False):
    value = os.environ.get(var_name, default)
    if required and value is None:
        raise ImproperlyConfigured(f'La variable de entorno {var_name} no está definida.')
    return value

# Clave para cifrado de campos sensibles (Fernet, AES-256+HMAC).
# Generar con:
#   from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())
FIELD_ENCRYPTION_KEY = 'DbQG9CWLvBRa8Iu9pv9fJDVURCdKYQQErlZ9oCYGsY8='
# Previous key used before introducing FIELD_ENCRYPTION_KEYS.  Including it
# here ensures older data encrypted with the original key can still be
# decrypted in developer setups without requiring extra environment variables.
_DEFAULT_FALLBACK = 'DbQG9CWLvBRa8Iu9pv9fJDVURCdKYQQErlZ9oCYGsY8='
FIELD_ENCRYPTION_FALLBACK_KEYS = os.environ.get(
    'FIELD_ENCRYPTION_FALLBACK_KEYS', _DEFAULT_FALLBACK
)
FIELD_ENCRYPTION_KEYS = [FIELD_ENCRYPTION_KEY] + [
    k for k in FIELD_ENCRYPTION_FALLBACK_KEYS.split(',') if k
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY
SECRET_KEY = get_env('SECRET_KEY', 'L3hesOa21ZGRsk0TsVvKMI6kWuv8d-ZAGIfP87i4Hv0')
DEBUG = False
ALLOWED_HOSTS = ['localhost','127.0.0.1','0.0.0.0','80.78.30.242']

# JWT
JWT_SECRET_KEY = get_env('JWT_SECRET_KEY', 'Ptf8454Jd55')

# URLs externas
# settings.py

# Configuración de endpoints del simulador, parametrizados vía .env
SIMULADOR_API_URL    = os.getenv('SIMULADOR_API_URL',    'http://localhost:3000/api/transferencia/')
SIMULADOR_TOKEN_URL  = os.getenv('SIMULADOR_TOKEN_URL',  'http://localhost:3000/api/login/')
SIMULADOR_VERIFY_URL = os.getenv('SIMULADOR_VERIFY_URL', 'http://localhost:3000/api/transferencia/verify/')
JWT_SECRET_KEY       = os.getenv('JWT_SECRET_KEY',       'Ptf8454Jd55')


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'banco.apps.BancoConfig',
    'django_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # JWT Authentication Middleware para proteger /api/
    'simulador_banco.middleware.jwt_auth.JWTAuthenticationMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ROOT_URLCONF = 'simulador_banco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simulador_banco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

LOGIN_URL = '/login/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'simulador_banco.middleware.allow_internal_network': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}

# Integraciones
TELEGRAM_BOT_TOKEN = get_env('TELEGRAM_BOT_TOKEN', '7881009139:AAH1mokuP0AjmCbd_tN3VJIxVkG7Fq95j5o')
TELEGRAM_CHAT_ID = get_env('TELEGRAM_CHAT_ID', '769077177')

OPENAI_API_KEY = get_env('OPENAI_API_KEY', '')
TOTP_SECRET = get_env('TOTP_SECRET', '')

SIMULATOR_NOTIFY_URL = 'http://localhost/notify'

